#Application properties
server:
  port: 8085


#AWS properties
cloud:
  aws:
    region:
      static: ap-south-1
    stack:
      auto: false
    credentials:
      accessKey: ASIAQ7P4EY27S5EZFC5T
      secretKey: msSCv9zfjpM3bXQyNQMsX3CJZhGabnNrc9U9tEH7
      sessiontoken: IQoJb3JpZ2luX2VjECoaCXVzLWVhc3QtMSJGMEQCIHjKSoAx5g5FyiGlUnhB3tvT2+U7bI8ZwQkB30/3eAxXAiBJM4dedY0tHDNIdlPi6CCdWwhmgvZZoUk9jJgtw+d3fyq8AggTEAEaDDA2NzYzNzY1OTMyNyIMkXN1G6wSsaLcmre8KpkCecByEuZinuxTFVWaqy2jxVCidanR86o66qDHrc2vn34cofhpR76/g1a+7sO7O7nKn7LjtQWjFPEdxlChwito1QpRWBeyiJsMdOFxBWvAWypeHTsFC2rLcBwq4rYV6scm6UkryZCzscNRc3wC09ORpc0RmyHtH+LUyHbWHh7GN92jltiMkfaWHMuLdIcoQlpljlf4ymcFkLH50p4xVO/wmFvbW55N3Mlbp81xDxTyA+EalY0OfQzEop9vlLllOw54vSc8EQ2QQa3Fg9q4CsgFPhpH3A7biOdxR6g2EDdvtQKsq5k2TD6ldItbBad9LpLsPbtUNzLtZ0LvS9s2LSDeI8LK2JEk3FYmbCURMs6LXvcOrkUm5ro8kK4wzOuAqAY6owFz1Pi/W1ui2LEUdmPM4UcOEnKjukHG9GQhA3AEYT5lB0kbY4Tr/w3u9ycXYAxlviBf9QPG7MxvDMAyR4RU2KaI5h7QY+EUdM6wFFIA5jz1YgJ+g7ROn48BigctWaFTq7cqBXR6DvkM02FlStuo4Ec5lhWJzs7jFr+pJgeW4Uq436Ytg6IqX4/rgZTYniIwk5HW4LLTtDmyZAqCVh2N6N47AF6q

application:
  bucket:
    name: 067637659327-xr-inception-mumbai-1

logging:
  level:
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error